### PR TITLE
This commit adds:

### PR DESCRIPTION
**Pull request by gbowne1**
- .gitignore with .DS_Store
- settings.json in .vscode
- adds new CODEOWNERS to that file representative of users who have contributed.

This commit changes/fixes:

Broken links to stylesheets in rfq.html

### CODE REVIEW

**Comment by gbowne1** [comment]
This is a semi major fix to one page which contained broken links to the CSS.

**Comment by pranavmadhu01** [comment]
I think the last css link should contain '../ ' in the front for each href.
eg:-href="../src/css/styles.css"
It is the proper way of representing it

**Comment by gbowne1** [comment]
I tried that.. didn't work.  Works fine now.

**Comment by gbowne1** [comment]
The pages are starting to look pretty good but need a lot of work still.

**Pull request merged**
