### PR TITLE
changed the footer

### PR DESCRIPTION
**Pull request by Darrkzero**

### CODE REVIEW

**Comment by gbowne1** [comment]
Looks great! Thanks for the PR! Merging

**Comment by Darrkzero** [comment]
You're welcome. Thanks for the review

**Comment by gbowne1** [comment]
Your are welcome.  I sent an invite to my group.

**Comment by Darrkzero** [comment]
Ok, i have accepted i will try my best contribute

**Comment by gbowne1** [comment]
There are some issues here.

https://github.com/taotnpwaft/website

**Pull request merged**
