### PR TITLE
contact page added

### PR DESCRIPTION
**Pull request by developer-irfan**
Hey @gbowne1 contact page added as per your requirments and map also added

-> Output

a

### CODE REVIEW

**Review by gbowne1 — APPROVED** [review]
Thats a good looking contact page. I will merge.

**Comment by gbowne1** [comment]
Hmm this has conflicts.  Unable to merge.

**Comment by developer-irfan** [comment]
> Hmm this has conflicts. Unable to merge.

conflict? which type of conflict?

**Comment by developer-irfan** [comment]
> GitHub just says this has merge conflicts so it is not able to merge. I will review and see what the problem is when I return later today it is early here

ok

**Comment by gbowne1** [comment]
I have a hunch it might be in styles.css though just looking at it

**Comment by developer-irfan** [comment]
@gbowne1 conflict removed check now. conflict in css file so i remove it. now you can merge it

**Comment by gbowne1** [comment]
That seems to have worked.. thanks. Merging

**Pull request merged**
