### PR TITLE
included bootstrap css/script links to index.html and revised "About" button links

### PR DESCRIPTION
**Pull request by SergeyKharkovshchenko**
image

    id: [issue-link](https://github.com/gbowne1/spmssite/issues/111)
    attributes:
      label: #111
      description: PR includes bootstrap in index.html and revises About button links

### CODE REVIEW

**Comment by gbowne1** [comment]
@SergeyKharkovshchenko This has merge conflicts.  Not able to merge this.

**Comment by developer-irfan** [comment]
@SergeyKharkovshchenko to resolve the conflict remove extra text from the code line '111', '125' and check if you put any other extra text then remove it.

**Comment by gbowne1** [comment]
@developer-irfan 

The only thing I see with this one is that there is already bootstrap CDN for both CSS and JS.  No need to add them again.  This will confuse the browser and the about links are just fine so I would not change them.  This PR can just be closed.

**Review by gbowne1 — COMMENTED** [review]
There is already Bootstrap CDN in line 14 through 21 of index.html for JS and CSS.

No need to add yet another CDN for it.  This will confuse the browser.

Also the about item link in line 80-82 works just fine.

This PR can be closed as not necessary.

**Comment by SergeyKharkovshchenko** [comment]
Hi, just to make sure, are you closing this PR?

**Pull request closed without merging**
