### PR TITLE
Add light/dark mode toggle in about.html

### PR DESCRIPTION
**Pull request by meikei-99**
*This is my first time opening a pull request, please advise me if I have made any mistakes. 

I have added a light/dark toggle on the about.html page. If everything is all right, I will then proceed to add them to the rest of the HTML page.

### CODE REVIEW

**Comment by salehghulamqasim** [comment]
you can simply put dark mode properties in css 
```

dark-mode {
  background-color: black;
  color: white;
}

```
then in html body link that with the javascript function 

`                        <button onclick="darkMode()"> Dark mode</button>
`

and then in script make this funtion


```
  <script>
            function darkMode() {
                var element = document.body;
                element.classList.toggle("dark-mode");
            }
  </script>
```

**Review by gbowne1 — COMMENTED** [review]
This looks ok. I would approve this merge.

It might be a bit heavy but the code looks good.

What do you think @Rmichal503 ?

**Comment by gbowne1** [comment]
I thought I read about something maybe on stackoverflow where you would write code that would detect the users preffered theme.

That is an option if it works.

**Comment by gbowne1** [comment]
@meikei-99 that worked in the About page about.html I was able to test it.

Thanks for the PR!

**Pull request merged**
