### PR TITLE
Big Fixes and additions

### PR DESCRIPTION
**Pull request by ketsebaotgizachew**
-have rebuild the darkmode functionality now it works on the index page too. and have made it easy to intergrate to other pages 
have properly themed the dark mode to be properly visible 
-have fixed the issue where the icons in the home page didnt have color and also did it for the two new icons
-and small ui fixes in about us and contact us pages

### CODE REVIEW

**Comment by ketsebaotgizachew** [comment]
any issues, I am open

**Comment by ketsebaotgizachew** [comment]
new darkmode
new

**Comment by gbowne1** [comment]
That looks great @ketse-py 

Approving merge

**Comment by ketsebaotgizachew** [comment]
> That looks great @ketse-py
> 
> Approving merge

the home page is empty is there a bluprint of what the home page is gonne contain so it can build in respect to that?

**Comment by gbowne1** [comment]
No there is no specific template.  This site project is intended to be a template site that an end user could use for their industrial /industrial workshop business.

I have seen that most industrial businesses are using Wordpress and  Divi theme from ElegantThemes with specific set of plugins.

While Wordpress and Divi theme are great, I highly suspect that whoever chose to use that did not reallly have a good alternative.

My goal for this sites theme is to be a lot better than that solution which is mainly a easy button solution in PHP

I can make a draw.io template based on what we have.

Ideally / root page or /index.html would display everything a customer or buyer would need to look at when choosing a business in that category.

**Comment by gbowne1** [comment]
also @ketsebaotgizachew 

The navbar is not consistent in and across all pages of the site. The way it exists in the current index.html is correct in how it should look, however, 

the Dropdown doen't even work and is not even correct. 

The dropdown should go (link) to the capabilities page (capabilities.html) and be called Capabilities instead of Dropdown.  Therein, the tabs in the dropdown should be:

- Services
- Equipment
- Materials 
- Industries

these should be # links to different sections of the capabilities.html page. so for instance you would have capabilites.html#materials.  ideally these references would be bootstrap v5.2 cards.

**Comment by ketsebaotgizachew** [comment]
i have tried to fix the dropdown but still dosent seem to work i have tried replacing it with a select and options it works but the options cant be styled that well

**Comment by ketsebaotgizachew** [comment]
fixed the dropdown I think this is what you meant 
and it navigates to capablities.html#services and etc...

dropdown

**Comment by gbowne1** [comment]
Yes, thats exactly it. @ketsebaotgizachew

**Comment by ketsebaotgizachew** [comment]
> Yes, thats exactly it. @ketsebaotgizachew

so the other two pages the contact and about page contain a navbar which has a lot of menus on it should I make it similar to the one on index.html

**Comment by gbowne1** [comment]
Minor things to add to this would be a dropdown to about linking to about.html and a # link to history section of he about page.

Also missing is a tab for quality and a tab named gallery  Have not decided whether that should be a part of About or another tab as a # link.

I would like to keep the number of pages in the site no more than 5 html pages/files.

Everything else can be modals, poppers, etc.

Oh and the one page with Google Maps in the footer.. thats the correct version of the footer to use in all the pages.

Contact page needs a little more text like "We would like to hear from you...".  

One last item to create would be to add a good looking carousel gallery of pictures in either about or one of the sections of capabities.

**Comment by gbowne1** [comment]
> > Yes, thats exactly it. @ketsebaotgizachew
> 
> so the other two pages the contact and about page contain a navbar which has a lot of menus on it should I make it similar to the one on index.html

Yes.  It should basically be the same.  Just set the #active property to each html page in the tab so it highlights whatever page youre viewing.

**Comment by gbowne1** [comment]
The rfq/quotes page has a very messed up navbar at the moment.

**Comment by ketsebaotgizachew** [comment]
fixed the rfq/quotes is this how it is supposed to look
rfq page

**Comment by ketsebaotgizachew** [comment]
fixed the rfq/quotes is this how it is supposed to look
rfq page

**Comment by gbowne1** [comment]
Yes @ketsebaotgizachew .  That is it.

**Comment by gbowne1** [comment]
This jobs/careers page also needs a careers or jobs section that shows job listings, HR contacts... stuff like that.  Not just a job application.

**Pull request merged**
