### PR TITLE
Bug fixes and themeing

### PR DESCRIPTION
**Pull request by ketsebaotgizachew**
-fixed the quotes page
-fixed the drop down menu and added an new one also named about us
-made the drop downs navigation work
-fixed the about us pages spacing
-fixed the quotes page theme and made it compatible with dark mode
-fixed the stiky navbar it works now

### CODE REVIEW

**Comment by gbowne1** [comment]
The dark mode switch shows in the search bar.

**Comment by pranavmadhu01** [comment]
I recommend everyone who is putting a pull request to attach an image with final results along with the result.Since it is a website all reviewers will get a  better understanding when an image is attached @ketsebaotgizachew can you  attach the screenshots as comment 
just use the snip tool and take a picture then paste it directly in to the comment.

**Comment by gbowne1** [comment]
Yeah @pranavmadhu01 I need to update the Contributing guide.  And that should be the same with TAOTNPWAFT

**Comment by ketsebaotgizachew** [comment]
drop-downs-working
navbar-stikyness
rfq page

**Comment by ketsebaotgizachew** [comment]
dark mode
i think the dark mode still needs more refinment

**Comment by gbowne1** [comment]
yeah, starting to look nice though.

As a side note: I have a whole bunch of great text to add that would be useful in about.

Accessibility is very important.  Especially when choosing themes and colors.

@ketsebaotgizachew move the 'Quotes' from About to its own tab.

**Comment by gbowne1** [comment]
@ketsebaotgizachew @ketse-py 

Make sure you PR your changes.  I saw a few commits without a PR.

Thank you.

**Comment by ketsebaotgizachew** [comment]
I am new to GitHub tho  so you have added me so I am able to commit directly to the repository so what are the pull requests for

**Comment by gbowne1** [comment]
Yes you can commit directly but you should still make pull requests from your local branch to the main branch.  

Ideally you would commit your changes to your branch ketsebaotgizachew:local-change-branch and then compare the changes with main and submit your PR.  

PRs keep any changes clean by requesting reviews of people within the project.

**Comment by gbowne1** [comment]
Yes you can commit directly but you should still make pull requests from your local branch to the main branch.  

Ideally you would commit your changes to your branch ketsebaotgizachew:local-change-branch and then compare the changes with main and submit your PR.  

PRs keep any changes clean by requesting reviews of people within the project.

One should read this: https://docs.github.com/en/get-started/quickstart/github-flow

**Comment by gbowne1** [comment]
https://nvie.com/posts/a-successful-git-branching-model/

**Pull request merged**
