### PR TITLE
- fixed darkmode toogle dislocating in firefox

### PR DESCRIPTION
**Pull request by ketsebaotgizachew**
corrected the problem works fine now
refox navbar

### CODE REVIEW

**Comment by ketsebaotgizachew** [comment]
@gbowne1

**Comment by ketsebaotgizachew** [comment]
@gbowne1

**Comment by gbowne1** [comment]
Yeah that looks better.  Thank you for the PR.

**Comment by gbowne1** [comment]
If you want me to review the changes, instead of @gbowne1 you can add me or anyone as a reviewer in the GitHub reviewers panel of the GitHub UI as you do the PR.

**Review by gbowne1 — COMMENTED** [review]
@ketse-py @ketsebaotgizachew 

Well...  I tested it this afternoon.  I synced and opened in Live Server.

Today's render in FF 104 (64 bit) Linux on Debian 11

Screenshot 2022-09-06 at 14-29-58 Seattle Precision Machine Shop

Incidentally, it's the same in my version of Chrome.

Version 105.0.5195.102 (Official Build) (64-bit) on Debian 11 Linux

**Comment by ketsebaotgizachew** [comment]
wierd let me test it

**Pull request merged**
