### PR TITLE
Added social icon in header section

### PR DESCRIPTION
**Pull request by VincentWoglo**
For issues: Add FontAwesome Social Icons #5
I added the social icons on the header section of the website

### CODE REVIEW

**Comment by gbowne1** [comment]
These now exist in the footer.  Social icons in the header are redundant.

This is the current render after todays changes.  See the footer  at the bottom of the page.

Screenshot 2022-08-16 at 14-37-26 Seattle Precision Machine Shop

**Comment by VincentWoglo** [comment]
So this issue is closed right? Also do you want me to design a front page for you in figma?

**Comment by gbowne1** [comment]
Yes, it was closed earlier today.  Yes a page design should be included as a Figma or in [draw.io](https://app.diagrams.net/).

Goal is to be on par or better than a Wordpress Divi theme/template.

**Review by gbowne1 — CHANGES_REQUESTED** [review]
These changes ahve already been fixed.

**Pull request closed without merging**
