### PR TITLE
This PR moves these changes back to main.

### PR DESCRIPTION
**Pull request by gbowne1**
fixed toggle dark mode and change its style to a button with moon.

Scrolling works again.

### CODE REVIEW

**Review by dk3775 — APPROVED** [review]
Looks Perfect Ready to Merge ✅

**Comment by gbowne1** [comment]
Light Mode 

Screenshot 2022-09-13 at 12-11-48 Seattle Precision Machine Shop

Dark Mode

Screenshot 2022-09-13 at 12-12-19 Seattle Precision Machine Shop

**Comment by developer-irfan** [comment]
@gbowne1 Looks amazing ready to merge

**Comment by gbowne1** [comment]
Yeah, I thought it was pretty good.  Thanks @developer-irfan

**Pull request merged**
